name: stateful_view_model
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/tappeddev/stateful_view_model
author: Tapped <contact@tapped.dev>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  rxdart: ^0.23.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.3.3
