name: stateful_view_model
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/tappeddev/stateful_view_model
author: Tapped <contact@tapped.dev>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.2.4
  rxdart: ^0.25.0

dev_dependencies:
  extra_pedantic: ^1.2.0
  test: ^1.3.3
