name: stateful_view_model
description: A starting point for Dart libraries or applications.
 version: 1.0.0
 homepage: https://github.com/tikkrapp/stateful_view_model
 author: Tikkr <info@tikkr.app>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
